language: python
env:
  matrix:
  - TOXENV=py27
  - TOXENV=py34
install:
  - pip install tox
  - pip install coverage
  - pip install codeclimate-test-reporter
script: tox
after_script:
  - codeclimate-test-reporter < lcov.info
notifications:
  email:
  - jon@linkedin.com
  - tpalino@linkedin.com
