language: python
matrix:
  include:
    - python: 2.6
      env:
      - TOXENV=py26
    - python: 2.7
      env:
      - TOXENV=py27
    - python: 3.4
      env:
      - TOXENV=py34
    - python: 3.5
      env:
      - TOXENV=py35
install:
  - pip install tox
  - pip install coveralls
  - pip install codeclimate-test-reporter
script: tox
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - codeclimate-test-reporter
  - coveralls
notifications:
  email:
  - jon@linkedin.com
  - tpalino@linkedin.com
